version: '3.8'

services:
  user-management-service:
    build:
      context: ./UserManagementService
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - postgres-db
      
  project-management-service:
    build:
      context: ./ProjectManagementService
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
    depends_on:
      - postgres-db
      
  resource-management-service:
    build:
      context: ./ResourceManagementService
      dockerfile: Dockerfile
    ports:
      - "5003:8080"
    depends_on:
      - postgres-db
      
  scheduling-service:
    build:
      context: ./SchedulingService
      dockerfile: Dockerfile
    ports:
      - "5004:8080"
    depends_on:
      - postgres-db
      
  document-management-service:
    build:
      context: ./DocumentManagementService
      dockerfile: Dockerfile
    ports:
      - "5005:8080"
    depends_on:
      - postgres-db
      
  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cpm
    ports:
      - "5432:5432"

  # rabbitmq:
  #     image: rabbitmq:3-management
  #     ports:
  #       - "5672:5672"
  #       - "15672:15672"
  
  api-gateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
      # Add dependencies for other services
